---

- hosts: all
  become: no
  remote_user: root
  gather_facts: False

### This takes care of making sure python2 is installed and if we want to run any plays locally in the future. Needed for Ubuntu 16.04 ###
    pre_tasks:
  - name: Check for ansible and install if missing, then gather facts
    raw: test -e /usr/bin/ansible || (apt install -y ansible)

  - setup: # gather_facts

  roles:
###  Main roles (Do not comment them out) ###
    - { role: common, tags: [ "common" ] } # install pre-requisites / upgrade apt / folder structure
    - { role: docker, tags: [ "docker" ] } # docker install / docker user setup
    - { role: ufw, tags: [ "ufw" ] } # firewall install