### https://github.com/portainer/portainer

- name: Create Portainer Config Directory
  file:
    path: /opt/docker/portainer
    mode: 0775
    state: directory
    recurse: yes

- name: Download and Run Portainer container
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    restart_policy: always
    volumes:
      - /opt/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "{{ portainer_port }}:9000"
    log_driver: syslog
    log_opt:
      tag: portainer

- name: Open Firewall port for Portainer
  ufw:
    rule: allow
    port: "{{ portainer_port }}"
    proto: tcp
    state: enabled