  - name: Upgrade apt to the latest packages
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Needed Programs and Dependencies
    apt:
      name: "{{ item }}"
      state: installed
    with_items:
    - linux-image-extra-virtual
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
    - wget
    - git
    - python-pip

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade

  - name: Install Pip tools 
    pip:
      name: "{{ item }}"
    with_items:
    - setuptools
    - docker-py
    - passlib


